#server
server:
  port: 9090 #spring boot server
  errror:
    include-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel.enabled: true

#Database
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/flab
    username: sa
    password:
